// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbj5wqKmvzNf91P7upeQclU2gTXMq6mc4',
    appId: '1:267938829982:web:c07837bdf97a7216f0cd8f',
    messagingSenderId: '267938829982',
    projectId: 'auth-flutter-d5a3c',
    authDomain: 'auth-flutter-d5a3c.firebaseapp.com',
    storageBucket: 'auth-flutter-d5a3c.appspot.com',
    measurementId: 'G-TJQCBZRFCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV18mxzcEOyTmkGbRu9qLGqSGfTN-fzfk',
    appId: '1:267938829982:android:8517ac02f227f56ff0cd8f',
    messagingSenderId: '267938829982',
    projectId: 'auth-flutter-d5a3c',
    storageBucket: 'auth-flutter-d5a3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4KTMvMe-uY2opJIJ0MuBkpVdLbTl28w',
    appId: '1:267938829982:ios:45d91c3d2793d55bf0cd8f',
    messagingSenderId: '267938829982',
    projectId: 'auth-flutter-d5a3c',
    storageBucket: 'auth-flutter-d5a3c.appspot.com',
    iosBundleId: 'com.example.authFlutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4KTMvMe-uY2opJIJ0MuBkpVdLbTl28w',
    appId: '1:267938829982:ios:45d91c3d2793d55bf0cd8f',
    messagingSenderId: '267938829982',
    projectId: 'auth-flutter-d5a3c',
    storageBucket: 'auth-flutter-d5a3c.appspot.com',
    iosBundleId: 'com.example.authFlutterWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbj5wqKmvzNf91P7upeQclU2gTXMq6mc4',
    appId: '1:267938829982:web:4982e5683a08c1c4f0cd8f',
    messagingSenderId: '267938829982',
    projectId: 'auth-flutter-d5a3c',
    authDomain: 'auth-flutter-d5a3c.firebaseapp.com',
    storageBucket: 'auth-flutter-d5a3c.appspot.com',
    measurementId: 'G-L2F4MYVH4B',
  );
}
